version: '3.3'
services:
    spa:
        build: ./client-app/
        ports:
            - "443:80"
        volumes: 
            - ./client-app/node_modules
            - .:/client-app
        networks: 
            - spa
            - api
        image: jbaker895/pathfinder-spa

    api:
        build: .
        ports: 
            - "5000:5000"
        networks: 
            - api
        image: jbaker895/pathfinder-api
networks: 
    spa:
    api: